name: Auto Enhance Issue
on:
  issues:
    types: [opened]

jobs:
  automation:
    if: contains(github.event.issue.labels.*.name, 'service-label')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Enhance Issue Body and Assign
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          USER_LOGIN: ${{ github.event.issue.user.login }}
          REPO: ${{ github.repository }}
        run: |
          CURRENT_BODY=$(gh issue view $ISSUE_NUMBER -R $REPO --json body --template '{{.body}}')
          NEW_BODY=$(printf "**ID:** %s\n\n%s\n\n---\nAuthor: @%s" "$ISSUE_TITLE" "$CURRENT_BODY" "$USER_LOGIN")
          gh issue edit $ISSUE_NUMBER -R $REPO \
            --add-assignee "$USER_LOGIN" \
            --body "$NEW_BODY" \
            --remove-label "automation-task"
